### Create a category group
POST http://localhost:3000/group HTTP/1.1
Content-Type: application/json

{
    "name": "Программное обеспечение"
}

### Create a parent category
POST http://localhost:3000/group/5fcc154c5d07240172f1f2cc/category HTTP/1.1
Content-Type: application/json

{
    "name": "Средства разработки"
}

### Create a subcategory
POST http://localhost:3000/group/5fcc154c5d07240172f1f2cc/category/5fcc15515d07240172f1f2cd/subcategory HTTP/1.1
Content-Type: application/json

{
    "name": "IDE",
    "specifications": [
      {
        "name": "Разработчик",
        "type": "radio",
        "values": [
          {
            "value": "JetBrains"
          },
          {
            "value": "Microsoft"
          }
        ]
      },
      {
        "name": "Поддерживаемые RAID-виртуализации обновленные",
        "type": "select",
        "values": [
          {
            "value": "Raid 0"
          },
          {
            "value": "Raid 1"
          },
          {
            "value": "Raid 120"
          }
        ]
      },
      {
        "name": "Количество слотов под сторадж",
        "type": "range",
        "range": {
          "minValue": 1,
          "maxValue": 45,
          "unit": "шт."
        }
      }
    ]
}

### Get subcategory products
GET http://localhost:3000/group/5fcc155c5d07240172f1f2ce/products?filters=%257B%2522price%2522%253Anull%252C%2522specifications%2522%253A%255B%257B%2522specificationId%2522%253A%25225fcc155c5d07240172f1f2d6%2522%252C%2522type%2522%253A%2522select%2522%252C%2522valueIds%2522%253A%255B%25225fcc155c5d07240172f1f2d8%2522%255D%257D%255D%257D&page=0&limit=10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjA3NTAxMjQ3LCJleHAiOjE2MDc1ODc2NDd9.IH-hL2Va7Dxs94MDz4VMmZmN2NGB61QBqK6ICtnEsxk

### Get all categories
GET http://localhost:3000/group HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjA3NTAxMjQ3LCJleHAiOjE2MDc1ODc2NDd9.IH-hL2Va7Dxs94MDz4VMmZmN2NGB61QBqK6ICtnEsxk

### Get a single category
GET http://localhost:3000/group/5fb9613f44109f0164f17393 HTTP/1.1

### Update a category
PUT http://localhost:3000/group/5fb96375557d52016b5c7370 HTTP/1.1
Content-Type: application/json

{
  "name": "Серверное оборудование"
}

### Delete a category
DELETE  http://localhost:3000/group/5fbb5c7bc327170190cd8725 HTTP/1.1
