version: '3.7'

services:
  pwa:
    container_name: 'pwa'
    build:
      context: .
      dockerfile: Dockerfile.pwa.dev
    restart: unless-stopped
    networks:
      - dev-network
    volumes:
      - type: bind
        source: ./pwa/public
        target: /usr/src/app/pwa/public
      - type: bind
        source: ./pwa/src
        target: /usr/src/app/pwa/src
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    container_name: 'api'
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    restart: unless-stopped
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - PORT=${API_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - dev-network
    volumes:
      - type: bind
        source: ./api/src
        target: /usr/src/app/api/src
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db

  db:
    image: mongo:4.1.8-xenial
    container_name: ${DB_HOSTNAME}
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
    ports:
      - 27017:27017
    networks:
      - dev-network
    command: mongod

networks:
  dev-network:
    driver: bridge

volumes:
  dbdata:
